// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package wifi

import (
	"github.com/mdlayher/wifi"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWiFiHandle creates a new instance of MockWiFiHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWiFiHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWiFiHandle {
	mock := &MockWiFiHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWiFiHandle is an autogenerated mock type for the WiFiHandle type
type MockWiFiHandle struct {
	mock.Mock
}

type MockWiFiHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWiFiHandle) EXPECT() *MockWiFiHandle_Expecter {
	return &MockWiFiHandle_Expecter{mock: &_m.Mock}
}

// Interfaces provides a mock function for the type MockWiFiHandle
func (_mock *MockWiFiHandle) Interfaces() ([]*wifi.Interface, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Interfaces")
	}

	var r0 []*wifi.Interface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*wifi.Interface, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*wifi.Interface); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*wifi.Interface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWiFiHandle_Interfaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Interfaces'
type MockWiFiHandle_Interfaces_Call struct {
	*mock.Call
}

// Interfaces is a helper method to define mock.On call
func (_e *MockWiFiHandle_Expecter) Interfaces() *MockWiFiHandle_Interfaces_Call {
	return &MockWiFiHandle_Interfaces_Call{Call: _e.mock.On("Interfaces")}
}

func (_c *MockWiFiHandle_Interfaces_Call) Run(run func()) *MockWiFiHandle_Interfaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWiFiHandle_Interfaces_Call) Return(interfaces []*wifi.Interface, err error) *MockWiFiHandle_Interfaces_Call {
	_c.Call.Return(interfaces, err)
	return _c
}

func (_c *MockWiFiHandle_Interfaces_Call) RunAndReturn(run func() ([]*wifi.Interface, error)) *MockWiFiHandle_Interfaces_Call {
	_c.Call.Return(run)
	return _c
}
